title: Yxa Rex - A Personal Website Of YR
description: Yashraj Maher's Personal Website a.k.a Yxa Rex's website which showcases Yashraj Maher's Projects and Interests.
url: https://rajofearth.github.io

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-get-json

# Permalink structure for blog posts
permalink: /blog/:year/:month/:day/:title/

collections:
  projects:
    output: true
    permalink: /projects/:path/
    
# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/